blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/ORG/echo-mode/security/policy
    about: Please report security vulnerabilities privately.
  - name: Boundary Concern (OSS vs Commercial)
    url: mailto:oss-boundary@echomode.io
    about: Report potential boundary issues privately.
